[package]
name = "azpfs"
version = "0.1.0"
edition = "2024"

[lib]
name = "libazpfs"
path = "src/core/mod.rs"

[[bin]]
name = "azpfsd"
path = "src/client/main.rs"

[[bin]]
name = "azpfs-server"
path = "src/server/main.rs"

[dependencies]
tokio = { version = "1.49", features = ["full"] }
clap = { version = "4.5.32", features = ["derive"] }
fuser = "0.17.0"
libc = "0.2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
